version: '3'
services:
  postgres:
    image: postgres
    env_file:
      - ./server/.development.env
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=attendance-db
    ports:
      - '5432:5432'
    volumes:
      - ./server/database/data/prod:/var/lib/postgresql/data

  # pgadmin:
  #   links:
  #     - postgres:postgres
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ./server/database/data/pgadmin:/root/.pgadmin
  #   env_file:
  #     - ./server/.development.env
  #   networks:
  #     - postgres

  apiserver:
    build:
      context: ./server
      dockerfile: ./Dockerfile #context 안에서 상대경로
    environment:
      - NODE_ENV=development
    command: ['yarn', 'start:dev']
    ports:
      - 3000:3000
    volumes:
      - ./server:/app:cached
    depends_on:
      - postgres

  # nginx:
  #   build:
  #     context: ./nginx
  #   ports:
  #     - 9090:443
  #   volumes:
  #     - ./nginx/cream.dev.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/dev-ssl:/etc/nginx/ssl

  # frontserver:
  #   build:
  #     context: ./client
  #     dockerfile: ./Dockerfile
  #   command: ['yarn', 'start']
  #   volumes:
  #     - ./client:/app:cached
