export const sharedTemplate = [
  {
    title: '수업명',
    dataIndex: 'lecName',
    key: 'lecName',
    width: '200px',
    align: 'center',
  },
  {
    title: '과목ID',
    dataIndex: 'lecID',
    key: 'lecID',
    width: '100px',
    align: 'center',
  },
  {
    title: '교사명',
    dataIndex: 'teaName',
    key: 'teaName',
    width: '150px',
    align: 'center',
  },

  {
    title: '학년',
    dataIndex: 'grade',
    key: 'grade',
    width: '87px',
    align: 'center',
  },

  {
    title: '반',
    dataIndex: 'classNum',
    key: 'classNum',
    width: '87px',
    align: 'center',
  },

  {
    title: '교시',
    dataIndex: 'time',
    key: 'time',
    width: '177px',
    align: 'center',
  },
]

export const shareLectures = [
  {
    id: '1',
    key: '1',
    lecName: '적분과통계',
    lecID: 12301,
    teaID: 101,
    teaName: '김교수',
    grade: 2,
    classNum: 1,
    time: '월3, 수5, 금3',
  },
  {
    id: '2',
    key: '2',
    lecName: '기하와벡터',
    lecID: 12501,
    teaID: 102,
    teaName: '이교수',
    grade: 2,
    classNum: 1,
    time: '화2, 목4',
  },

  {
    id: '3',
    key: '3',
    lecName: '영어',
    lecID: 31201,
    teaID: 103,
    teaName: '박교수',
    grade: 2,
    classNum: 1,
    time: '화3, 수6, 목3',
  },

  {
    id: '4',
    key: '4',
    lecName: '생명과학1',
    lecID: 45601,
    teaID: 104,
    teaName: '최교수',
    grade: 2,
    classNum: 1,
    time: '월1, 목2',
  },
  {
    id: '5',
    key: '5',
    lecName: '물리1',
    lecID: 45602,
    teaID: 105,
    teaName: '이교수',
    grade: 2,
    classNum: 1,
    time: '화3, 금6',
  },
]

export const shareStudents = [
  {
    id: '1',
    key: '1',
    uID: 10000,
    email: 'kcs@example.com',
    name: '김철수',
    type: 'S',
    phone: '01012345678',
    grade: 4,
    classNum: 2,
    studentNum: 1,
    attendanceState: null,
  },
  {
    id: '2',
    key: '2',
    uID: 10001,
    email: 'kcs@example.com',
    name: '김영희',
    type: 'S',
    phone: '01012345678',
    grade: 4,
    classNum: 2,
    studentNum: 2,
    attendanceState: 'attendance',
  },
  {
    id: '3',
    key: '3',
    uID: 10002,
    email: 'kcs@example.com',
    name: '박철수',
    type: 'S',
    phone: '01012345678',
    grade: 4,
    classNum: 2,
    studentNum: 3,
    attendanceState: 'absent',
  },
  {
    id: '4',
    key: '4',
    uID: 10003,
    email: 'kcs@example.com',
    name: '홍길동',
    type: 'S',
    phone: '01012345678',
    grade: 4,
    classNum: 2,
    studentNum: 4,
    attendanceState: 'attendance',
  },
  {
    id: '5',
    key: '5',
    uID: 10004,
    email: 'kcs@example.com',
    name: '이철수',
    type: 'S',
    phone: '01012345678',
    grade: 4,
    classNum: 2,
    studentNum: 5,
    attendanceState: 'tardy',
  },
  {
    id: '6',
    key: '6',
    uID: 10005,
    email: 'kcs@example.com',
    name: '이영희',
    type: 'S',
    phone: '01012345678',
    grade: 4,
    classNum: 2,
    studentNum: 6,
    attendanceState: 'etc',
  },
]
